version: '3.9'

services:
  app:
    container_name: dot-articles-service
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
