name: Deployment Production

on: workflow_dispatch

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend
          tags: |
            type=sha

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  deploy-to-server:
    runs-on: self-hosted
    needs: build-docker-image
    steps:
      - name: Deploy new image
        run: |
          cd /home/mettle/dot-articles && TAG=${{ needs.build-docker-image.outputs.image_tag }} docker compose up -d
